POST http://localhost:8000/api/register
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "test2@gmail.com",
    "password": "password",
    "password_confirmation": "password"
}
###
GET http://localhost:8000/api/user
Authorization: Bearer 3|Hku4q5oRTgeIhtSaM4ZyHaj05HZB9LTQaXhBjaG4

###
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "password"
}

###
POST http://localhost:8000/api/logout
Authorization: Bearer 3|Hku4q5oRTgeIhtSaM4ZyHaj05HZB9LTQaXhBjaG4

###
GET http://localhost:8000/api/budget
Authorization: Bearer 5|q5iRk8ALQ2ekrzXeRPs0QMFx09yujPoy5zIG8g0A

###
POST http://localhost:8000/api/budget
Authorization: Bearer 5|q5iRk8ALQ2ekrzXeRPs0QMFx09yujPoy5zIG8g0A
Content-Type: application/json

{
    "total_budget": 1000000,
}